# Created with YamlCreate.ps1 v2.3.3 $debug=QUSU.CRLF.5-1-22621-2506.Win32NT
# yaml-language-server: $schema=https://raw.githubusercontent.com/microsoft/winget-cli/master/schemas/JSON/manifests/v1.6.0/manifest.defaultLocale.1.6.0.json

PackageIdentifier: AirDroid.AirDroid
PackageVersion: 3.7.2.1
PackageLocale: en-US
Publisher: Sand Studio
# PublisherUrl:
PublisherSupportUrl: https://airdroid.com/remote-support-software
PrivacyUrl: https://airdroid.com/legal/privacy.html?type=business
# Author:
PackageName: AirDroid
PackageUrl: https://www.airdroid.com
License: Proprietary
# LicenseUrl:
Copyright: © 2011-2021 Sand Studio, Singapore
# CopyrightUrl:
ShortDescription: App for integration between Windows and Android
# Description:
Moniker: airdroid
# Tags:
# ReleaseNotes:
# ReleaseNotesUrl:
# PurchaseUrl:
# InstallationNotes:
Documentations:
- DocumentLabel: FAQ
  DocumentUrl: https://help.airdroid.com
ManifestType: defaultLocale
ManifestVersion: 1.6.0
